export const FETCHING_BOOKS_REQUEST  = "FETCHING_BOOKS_REQUEST";
export const FETCHING_BOOKS_SUCCESS  = "FETCHING_BOOKS_SUCCESS";
export const FETCHING_BOOKS_FAILURE  = "FETCHING_BOOKS_FAILURE";

export const TITLE_ADD = "TITLE_ADD";
export const DESCRIPTION_ADD = "DESCRIPTION_ADD";
export const ADD_BOOKS = "ADD_BOOKS";
export const ADD_BOOKS_SUCCESS = "ADD_BOOKS_SUCCESS";
export const ADD_BOOKS_FAILURE = "ADD_BOOKS_FAILURE";
export const CLEAR_POSTS =  'CLEAR_POSTS';
export const SELECT_BOOKS = "SELECT_BOOKS";
